#!/usr/bin/env python

#
# gerber2graphtec
#
# Cut fine-pitch SMT stencils from a gerber file using a Graphtec craft/vinyl cutter (e.g. Silhouette Cameo or Portrait)
#
# Copyright (c) 2012 Peter Monta <pmonta@gmail.com>
#

import sys
import os
import string
import argparse

import graphtec
import pic
import optimize
import distutils

merge_threshold = [0.012, 0.01]




def main():
    # Parse arguments.
    floats = lambda s: map(float,string.split(s,','))

    parser = argparse.ArgumentParser()
    parser.add_argument('--offset', type=floats, default=[4,0.5],
        help='translate to device coordinates x,y (inches) (default: 4,0.5)')
    parser.add_argument('--border', type=floats, default=[1,1],
        help='cut a border around the bounding box of the gerber file; 0,0 to disable (default: 1,1)')
    parser.add_argument('--matrix', type=floats, default=[1,0,0,1],
        help='transform coordinates by [a b;c d] (default: identity transform 1,0,0,1)')
    parser.add_argument('--speed', type=floats, default=[2,2],
        help='use speed s in device units; s2,s3 for multiple passes (default: 2 passes, speed 2 in each pass)')
    parser.add_argument('--force', type=floats, default=[8,30],
        help='use force f in device units; f2,f3 for multiple passes (default: first pass 8, second pass 30)')
    parser.add_argument('--cut_mode', type=int, choices=[0,1], default=0,
        help='0 for highest accuracy (fine pitch), 1 for highest speed (default: 0)')
    parser.add_argument('--media_size', type=floats, default=[12,11],
        help='size of media (default: 12x11 inches)')
    parser.add_argument('--rotate', type=float, dest='theta', default=0.,
        help='rotate counterclockwise by theta degrees (default: no rotation)')
    parser.add_argument('--merge', type=int, choices=[0,1], default=0,
        help='merge close smaller structures into one big cutout (default: 0)')
    parser.add_argument('input_filename')
    args = parser.parse_args()


    # Check dependencies.
    allowed_inkscape_files = ('svg', 'dxf')
    
    if distutils.spawn.find_executable("pstoedit") is None:
        print("FATAL ERROR: Could not find 'pstoedit' in your PATH. Exiting.")
        sys.exit(1)
    if distutils.spawn.find_executable("gerbv") is None:
        print("ERROR: Could not find 'gerbv' in your PATH. Exiting")
        sys.exit(1)
    if distutils.spawn.find_executable("inkscape") is None and input_filename[-3:].lower() in allowed_inkscape_files:
        print("ERROR: Could not find 'inkscape' in your PATH. Exiting")
        sys.exit(1)


    temp_pdf = "_tmp_gerber.pdf"
    temp_ps  = "_tmp_gerber.ps"
    temp_pic = "_tmp_gerber.pic"

    pdf_filename = args.input_filename
    extension = pdf_filename[-3:].lower()

    # If file is not a PDF, try to convert it to one.
    if extension != "pdf":
      if extension in allowed_inkscape_files:
        os.system(f"inkscape --export-filename={temp_pdf} {pdf_filename}")
      else:
        os.system(f"gerbv --export=pdf --output='{temp_pdf}' --border=0 '{args.input_filename}'")
      pdf_filename = temp_pdf

    # Convert PDF to PIC format.
    os.system(f"gs -dNOPAUSE -dBATCH -sDEVICE=ps2write -sOutputFile='{temp_ps}' '{pdf_filename}'")
    os.system(f"pstoedit -f pic '{temp_ps}' '{temp_pic}' 2>/dev/null")


    # Convert to Graphtec.
    g = graphtec.graphtec()
    g.set(media_size=args.media_size)
    offset, border = args.offset, args.border
    g.set(offset=(offset[0]+border[0]+0.5,offset[1]+border[1]+0.5))
    g.set(matrix=args.matrix)
    g.start()

    strokes = pic.read_pic(temp_pic)

    # Optionally merge multiple smaller pads into bigger pads spanning the same area.
    if not args.merge == 0:
      import mergepads
      strokes = mergepads.fix_small_geometry(strokes, merge_threshold[0], merge_threshold[1])

    strokes = optimize.rotate(strokes, args.theta)
    strokes = optimize.justify(strokes)
    max_x,max_y = optimize.max_extent(strokes)

    border_path = [
      (-border[0], -border[1]),
      (max_x+border[0], -border[1]),
      (max_x+border[0], max_y+border[1]),
      (-border[0], max_y+border[1])
    ]

    for (s,f) in zip(args.speed, args.force):
      g.set(speed=s, force=f)
      if args.cut_mode==0:
        lines = optimize.optimize(strokes, border)
        for x in lines:
          g.line(*x)
      else:
        for s in strokes:
          g.closed_path(s)
      if border != [0, 0]:
        g.closed_path(border_path)

    g.end()




if __name__ == "__main__":
    main()
